/**
 * @license
 * Copyright (c) 2018 The Polymer Project Authors. All rights reserved.
 * This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 * The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 * The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 * Code distributed by Google as part of the polymer project is also
 * subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
 */
(function(){"use strict";var e,n=!1,t=[],o=!1;function r(){window.WebComponents.ready=!0,document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))}function d(){window.customElements&&customElements.polyfillWrapFlushCallback&&customElements.polyfillWrapFlushCallback((function(n){e=n,o&&e()}))}function i(){d(),c()}function c(){window.HTMLTemplateElement&&HTMLTemplateElement.bootstrap&&HTMLTemplateElement.bootstrap(window.document),n=!0,a().then(r)}function a(){o=!1;var n=t.map((function(e){return e instanceof Function?e():e}));return t=[],Promise.all(n).then((function(){o=!0,e&&e()})).catch((function(e){console.error(e)}))}window.WebComponents=window.WebComponents||{},window.WebComponents.ready=window.WebComponents.ready||!1,window.WebComponents.waitFor=window.WebComponents.waitFor||function(e){e&&(t.push(e),n&&a())},window.WebComponents._batchCustomElements=d;var s="webcomponents-loader.js",l=[];(!("attachShadow"in Element.prototype)||!("getRootNode"in Element.prototype)||window.ShadyDOM&&window.ShadyDOM.force)&&l.push("sd"),window.customElements&&!window.customElements.forcePolyfill||l.push("ce");var w=function(){var e=document.createElement("template");if(!("content"in e))return!0;if(!(e.content.cloneNode()instanceof DocumentFragment))return!0;var n=document.createElement("template");n.content.appendChild(document.createElement("div")),e.content.appendChild(n);var t=e.cloneNode(!0);return 0===t.content.childNodes.length||0===t.content.firstChild.content.childNodes.length}();if(window.Promise&&Array.from&&window.URL&&window.Symbol&&!w||(l=["sd-ce-pf"]),l.length){var m,u=function(){var e=function(e){return e},n={createHTML:e,createScript:e,createScriptURL:e},t=window.trustedTypes&&window.trustedTypes.createPolicy("webcomponents-loader",n);return t||n}(),p="bundles/webcomponents-"+l.join("-")+".js";if(window.WebComponents.root)m=window.WebComponents.root+p,window.trustedTypes&&window.trustedTypes.isScriptURL(window.WebComponents.root)&&(m=u.createScriptURL(m));else{var f=document.querySelector('script[src*="'+s+'"]');m=u.createScriptURL(f.src.replace(s,p))}var b=document.createElement("script");b.src=m,"loading"===document.readyState?(b.setAttribute("onload",u.createScript("window.WebComponents._batchCustomElements()")),document.write(u.createHTML(b.outerHTML)),document.addEventListener("DOMContentLoaded",c)):(b.addEventListener("load",(function(){i()})),b.addEventListener("error",(function(){throw new Error("Could not load polyfill bundle"+m)})),document.head.appendChild(b))}else"complete"===document.readyState?(n=!0,r()):(window.addEventListener("load",c),window.addEventListener("DOMContentLoaded",(function(){window.removeEventListener("load",c),c()})))})();